name: Deploy jws to modula

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to modula/jws
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: joaomrpimentel/modula
          publish_branch: deploy
          publish_dir: .
          destination_dir: jws
